/*
-- Query: SELECT * FROM icc.`task-master`
LIMIT 0, 1000

-- Date: 2018-08-13 17:43
*/
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('06e2387a-2213-11e8-9339-00505695313b','398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'Department Master','item',NULL,'',NULL,'/apps/organization/departments',NULL,NULL,NULL,NULL,NULL,'Department Maintenance',0,'/organization/department','Manage Departments',NULL,'2018-04-23 07:09:16',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('1c2d5eee-ef6e-42b4-92c5-596e9ac5eeb6','a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'Devotee View','item',NULL,'account_box',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Devotee View',0,'/devotee/view','Read only View of Devotee Contact Information','2018-05-15 05:48:13','2018-05-15 05:48:13',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('23d2c615-17ea-4070-914b-bea2385cf988',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Event Planner',0,'/organization/event/eventPlanner','Event Planner','2018-05-21 04:13:33','2018-05-21 04:13:33',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'22c52dcb-9ec0-11e8-a9a5-d4bed99b600a','Organization','collapsable',NULL,'group',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,'2018-08-13 12:10:54',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('4108ff76-1ac5-11e8-a069-20cf308ebc45','398860cb-9ec7-11e8-a445-d4bed99b600a','','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Manage List Master Data',0,'/lookupMaster','Add / Edit Master Data or List of Values',NULL,NULL,NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('4667aec9-444f-11e8-a8f0-00505695313b',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Announcements List',0,'/announcements','Announcements List',NULL,'2018-04-23 10:36:51',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('58f4d8fb-2212-11e8-9339-00505695313b','398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'Task Master','item',NULL,'',NULL,'/apps/organization/tasks',NULL,NULL,NULL,NULL,NULL,'Task Master Data',0,'/organization/task','Add / Edit Task Master Data',NULL,NULL,NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('732e8c74-2d7e-11e8-b8e7-00505695313b','a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'Mange Devotee Data','item',NULL,'account_box',NULL,'/apps/devotees',NULL,NULL,NULL,NULL,NULL,'Mange Devotee Data',0,'/devotee/manage','Search and Manage Devotee Data associated to the temple',NULL,'2018-05-15 05:49:38',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('80520182-fe9e-4728-b3c7-26d4e40f6431','a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'Devotee Service','item',NULL,'account_box',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Devotee Service',0,'/devotee/service','Services Devotees are interested in','2018-05-17 03:21:33','2018-05-17 03:21:33',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('8404d20f-42fd-4f9e-8d14-21368e8a1cb0','398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'Services Master','item',NULL,'',NULL,'/apps/organization/services',NULL,NULL,NULL,NULL,NULL,'Services Master Data',0,'/organization/service','Services related to Temple','2018-04-23 07:39:28','2018-04-23 07:39:28',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('9284409e-4316-11e8-acd3-00505695313b',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'My Services',0,'/myServices','Manage My Services',NULL,NULL,NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'22c52cd8-9ec0-11e8-a9a5-d4bed99b600a','Devotee Database','collapsable',NULL,'account_box',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('c6564b7b-1200-41b7-a8bb-738695c5f219',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Event Master',0,'/organization/event/eventMaster','Events such as festivals, Maharaj Visits, etc','2018-05-07 04:28:46','2018-05-07 04:28:46',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('e7ef7d35-1bbb-11e8-9336-00505695313b','a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'Devotee Role Mapping','item',NULL,'account_box',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Devotee Role Mapping',0,'/devoteeRole','Manage Role Mappings to Devotees',NULL,'2018-04-23 06:53:20',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('e819a323-1ddf-11e8-8d69-20cf308ebc45','398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'Role Master','item',NULL,'',NULL,'/apps/organization/roles',NULL,NULL,NULL,NULL,NULL,'Role Data Maintenance',0,'/organization/role','Add / Edit Organization Roles',NULL,NULL,NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('eaacd33d-0af4-4325-a13d-a310bd43e458','398860cb-9ec7-11e8-a445-d4bed99b600a',NULL,'Role Task Assignment','item',NULL,'',NULL,'/apps/organization/roleTasks',NULL,NULL,NULL,NULL,NULL,'Role Task Assignment',0,'/organization/roleTask','Assign Tasks to a Role','2018-04-24 02:46:10','2018-04-24 02:46:10',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('f662c8f8-31e7-4579-a715-0c84721b1201',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Event Calendar',0,'/organization/eventCalendar','List of Public and Internal Eents','2018-05-01 03:54:58','2018-05-01 03:54:58',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('fb076075-9e20-495d-8036-870df61dfc7b',NULL,'','','',NULL,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Fund Instrument Maintenance',0,'/finance/receivables/funRaising/fundInstrument','Fund Instrument Maintenance','2018-05-19 05:39:50','2018-05-19 05:39:50',NULL,NULL);
INSERT INTO `task-master` (`id`,`parent-id`,`task-group-id`,`title`,`type`,`translate`,`icon`,`hidden`,`url`,`classes`,`exactMatch`,`externalURL`,`openInNewTab`,`function`,`task-name`,`approval-rules-apply-ind`,`application-route`,`task-description`,`created-on`,`updated-on`,`created-by`,`updated-by`) VALUES ('fc2a2ad7-85a3-4baf-bbe4-b9bac39227d8','a73f4735-9ec0-11e8-a9a5-d4bed99b600a',NULL,'Devotee Grouping','item',NULL,'account_box',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Devotee Grouping',0,'/devotee/group','Grouping of Devotees for Various Communications','2018-04-29 03:16:44','2018-04-29 03:16:44',NULL,NULL);
